                       -----------------------------
                       | Columns Registration Form |
                       -----------------------------  v1.00

Name    : ___________________________________________________________

e-mail  : ___________________________________________________________

(if no e-mail:)
address : ___________________________________________________________
          ___________________________________________________________
          ___________________________________________________________
          ___________________________________________________________
          ___________________________________________________________

where did you hear about Columns? ___________________________________


Please remember to include the cheque for £10 sterling, made payable to
  JS Greenwood

and mail all this to:
  JS Greenwood
   113 Crosland Road
    Oakes
     Huddersfield
      West Yorkshire
      HD3 3PW
      England


Thankyou for supporting shareware.
