Worm 1.0   Psion Series 5
-------------------------

FreeWare program  '98 szeptember

A Worm program telep¡t‚se:

1) Gy“z“dj meg arr¢l, hogy a \System\Apps k”nyvt rat l tod-e.
   Ha nem, enged‚lyezd a 'Preferences' be ll¡t sokn l.
2) Menj a \System\Apps k”nyvt rba ‚s k‚sz¡ts egy £j folder-t "Worm" n‚vvel
3) A PSIWIN, vagy egy‚b program haszn lat val m sold  t ezeket a file-okat
   a most keletkezett \System\Apps\Worm folder-be.
4) Ennyi! Megjelent egy £j ikon az Extras bar alatt.
--------------------------------------------------------------------------

A j t‚k:

A j t‚kot a Game/New game menponttal, vagy gyorsabban a CTRL+N billenty–kkel
ind¡tsd.

Egy kukacot kell  tvezetned (jelen verzi¢ szerint) 13 szob n. Minden szob ban
10 levelet kell megenned ahhoz, hogy megjelenjen a kij rat. (Vigy zz, el‚g
kicsi, neh‚z ‚szrevenni.) A kij rat megjelen‚sekor figyelmeztet“ hangot
hallhatsz. Ekkor, ha el‚g gyorsan felfaltad a leveleket m‚g van id“d kimenni.
A rendelkez‚sedre  ll¢ id“ letelte el“tti 5 m sodperct“l figyelmeztet“
pittyeg‚seket hallhatsz m sodpercenk‚nt. Ha nem jutott l ki, £jabb 10 levelet
kapsz. s a fentiek ism‚tl“dnek. Ha megint nem jutsz ki, m‚g egy etet‚s
t”rt‚nik. Ez az utols¢, de most valamivel t”bb id“d van, mint az els“ kett“n‚l.
Ha most sem jutsz ki, elfogyott a leveg“d, s egy kukac meghalt.

A kukac mozgat sa alap‚rtelmez‚s szerint a kurzormozgat¢ billenty–kkel
t”rt‚nik. Ha nem felel meg, megadhatsz m st is. A menben Keys/redefine Keys
menpont alatt, vagy gyorsabban a CTRL+K billenty–kkel. Ekkor a megjelen“ ablak
als¢ r‚sz‚ben l thatod az ‚ppen aktu lis billenty–ket.
A be ll¡t shoz el“sz”r nyomd le a megadni k¡v nt ir nyt mutat¢ kurzormozgat¢
billenty–t, majd azt a billenty–t, amit erre az ir nyra haszn lni szeretn‚l.
Ezt a k‚t l‚p‚st ism‚teld az ”sszes ir nyra. V‚g‚n ss ESC-et.
A Key/Cursor keys men ind¡t s val (CTRL+C) vissza ll¡thatod az eredeti
kurzormozgat¢ billenty–ket.

A kukac nem tk”zhet saj t mag ba, a szob ban l‚v“ t rgyakba, ‚s a falba sem.
Ha ezt teszi, ‚let‚vel fizet ‚rte.

Ahogy az id“ telik, a kukac egyre gyorsabban mozog.

Sznetet a space billenty–vel iktathatsz be, ENTER-rel folytathatod a j t‚kot.

A k‚perny“ jobb oldal n a k”vetkez“ket l thatod:

        R:XIII : a szoba sz ma
        T:129  : marad‚k id“
        3/10   : h rmat megett‚l a t¡z lev‚lb“l
        P: 53  : pontjaid sz ma
        L:  3  : ‚leteid (kukacaid) sz ma

Ha egy p ly n t£ljutott l, kapsz egy k¢dot, amivel legk”zelebb m r a k”vetkez“
szob ban kezdheted. Erre a Game/Level men alatt (CTRL+L) van lehet“s‚g. Ekkor
a Game/New game m r a megadott szob ba helyez T‚ged.


Ha gondod van, vagy fejleszt‚si ”tleted t madt, ¡rj

E-mail: sarlos@finit.hu

Sarl¢s Ferenc
