"Applikation ist bereits
"installiert auf Disk
"Weiter
"Andere Disk
"Nur Optionen
"WÑhle Disk
"System Disk
"Daten Disk
"Kopiere
"Nein
"Ja
"Abbruch
"Transfer abgebrochen
"gelîscht
"Transfer beendet
"existiert
"Installieren Sie
"von
"disk
"I vom Systemschirm
"Optionen wurden installiert
"Åberschreiben?
"mit Fehlern
"Sicherung
; w=Weiter,a=Andere Disk,o=Nur Optionen,j=ja,n=nein
"waojn
"EXIT
"Bitte machen Sie eine Daten-
"sicherung bevor Sie installieren.
""Intern"
"PicPoc S3a Installation
PPicPoc erst deinstallieren
PSystemtaste, zu PicPoc
Pnavigieren, dann PSION-E
P?
A\app\picpoc.opa
?F
F\pic
?2+
?3+
?4+
IOptionenauswahl(25k+)
?1Weitere Fonts(5k)
?2Beispiele(3k)
?3Weitere Umrisse(1k)
?4Handbuch(10k)
D
!F
+R\app\picpoc.opa
+Rpiclan_g.opa,\app\picpoc\piclan.opa
+R\app\picpoc\pattern?.pic
+R\app\picpoc\shape0.pic
+R\app\picpoc\shape1.pic
!2
+R@:\pic\picpoc.pic
+R@:\pic\tree.pic
!3
+C\app\picpoc\shape2.pic
+C\app\picpoc\shape3.pic
+C\app\picpoc\shape4.pic
!4
+R\wrd\picpoc.wrd
!1
+R\app\picpoc\*.fon


