"The application is already
"installed on drive
"Continue
"Other drive
"Options only
"Select drives
"System Drive
"Data Drive
"Copying
"No
"Yes
"Abort
"Transfer aborted
"deleted
"Transfer completed
"exists
"Install
"from
"drive
"I from system screen
"Additional options were installed
"Overwrite?
"with errors
"Backup
; c=continue,d=other drive,o=option only,y=yes,n=no
"cdoyn
"EXIT
"Please make a backup of your
"files before you continue.
"Internal
"PicPoc S3 Installation
PPlease deinstall PicPoc first.
PSystem key, navigate to PicPoc
M
+Pthen PSION-\.
-Pthen PSION-Y.
P?
A\app\picpoc.opa
?F
F\pic
?2+
?3+
?4+
ISelect options(22k+)
?1AdditonalFonts(5k)
?2Examples(1k)
?3More pen shapes(1k)
?4Online manual(10k)
D
!F
+R\app\picpoc.opa
+R\app\picpoc\piclan.opa
+R\app\picpoc\pattern?.pic
+R\app\picpoc\shape0.pic
+R\app\picpoc\shape1.pic
!1
+R\app\picpoc\*.fon
!2
+R@:\pic\picpoc.pic
+R@:\pic\tree.pic
!3
+C\app\picpoc\shape2.pic
+C\app\picpoc\shape3.pic
+C\app\picpoc\shape4.pic
!4
+R\wrd\picpoc.wrd


