;---------------------------------
; Task Switcher configuration file
;---------------------------------

HotKey=9    ; Tab
HotShift=4  ; Ctrl

StayOn=0
UseGrey=1
AwakeOnPower=0

ProcHide=SYS$IR.IMG
ProcHide=SYS$TIP.IMG
ProcHide=SYS$RPCS.IMG

ProcIcon=IMG,ROM::RUNIMG.APP
ProcIcon=OPO,ROM::RUNOPL.APP

FileIcon=JOT,ROM::JOTTER.ALS
FileIcon=OPL,ROM::PROGRAM.ALS

;Process to Hide On a Workabout
;ProcHide=SYS$SHLL.IMG
