[Control Panel\Cursors]
Arrow=c:\temp\PSION Normale Auswahl.cur
Help=c:\temp\PSION Hilfeauswahl.cur
AppStarting=c:\temp\PSIONH~1.ani
Wait=c:\temp\PSION Ausgelastet.ani
NWPen=c:\temp\PSION Handschrift.cur
No=c:\temp\PSIONN~1.cur
SizeNS=c:\temp\PSIONV~1.cur
SizeWE=c:\temp\PSIONH~2.cur
Crosshair=c:\temp\PSIONP~1.cur
IBeam=c:\temp\PSION Textauswahl.cur
SizeNWSE=c:\temp\PSIOND~2.cur
SizeNESW=c:\temp\PSIOND~1.cur
SizeAll=c:\temp\PSION Bewegung.cur
UpArrow=c:\temp\PSION Alternative Auswahl.cur
DefaultValue=

[Control Panel\Desktop]
Wallpaper=c:\temp\epoc_power_ii.jpg
TileWallpaper=0
WallpaperStyle=2
ScreenSaveActive=1

[AppEvents\Schemes\Apps\.Default\.Default\.Current]
DefaultValue=c:\temp\Kirchenglocken.wav

[AppEvents\Schemes\Apps\.Default\AppGPFault\.Current]
DefaultValue=c:\temp\Fanfare.wav

[AppEvents\Schemes\Apps\.Default\Maximize\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\MenuCommand\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\MenuPopup\.Current]
DefaultValue=c:\temp\PSIONM~1.wav

[AppEvents\Schemes\Apps\.Default\Minimize\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\Open\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\Close\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\RestoreDown\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\RestoreUp\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\RingIn\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\Ringout\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SystemAsterisk\.Current]
DefaultValue=c:\temp\Kirchenglocken.wav

[AppEvents\Schemes\Apps\.Default\SystemDefault\.Current]
DefaultValue=c:\temp\Standuhr.wav

[AppEvents\Schemes\Apps\.Default\SystemExclamation\.Current]
DefaultValue=c:\temp\Fanfare.wav

[AppEvents\Schemes\Apps\.Default\SystemExit\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SystemHand\.Current]
DefaultValue=c:\temp\Fanfare.wav

[AppEvents\Schemes\Apps\.Default\SystemQuestion\.Current]
DefaultValue=c:\temp\Standuhr.wav

[AppEvents\Schemes\Apps\.Default\SystemStart\.Current]
DefaultValue=c:\temp\Westminster.wav

[AppEvents\Schemes\Apps\Explorer\EmptyRecycleBin\.Current]
DefaultValue=

[Control Panel\Colors]
ActiveTitle=255 128 0
Background=0 0 128
Hilight=240 184 40
HilightText=255 255 255
TitleText=255 255 255
Window=255 255 255
WindowText=0 0 0
Scrollbar=232 232 232
InactiveTitle=0 0 128
Menu=208 208 208
WindowFrame=0 0 0
MenuText=0 0 0
ActiveBorder=207 207 209
InactiveBorder=207 207 209
AppWorkspace=136 136 140
ButtonFace=208 208 208
ButtonShadow=136 136 144
GrayText=136 136 144
ButtonText=0 0 0
InactiveTitleText=255 255 255
ButtonHilight=232 232 232
ButtonDkShadow=0 0 0
ButtonLight=208 208 208
InfoText=0 0 0
InfoWindow=255 255 225
GradientActiveTitle=232 176 0
GradientInactiveTitle=0 0 255

[boot]
SCRNSAVE.EXE=c:\temp\movplayr.scr

[WebView]
WVLEFT.BMP=c:\temp\PSIONW~1.BMP
WVLINE.GIF=c:\temp\PSIONW~1.GIF

[MasterThemeSelector]
MTSM=DABJDKT

[Metrics]
IconMetrics=76 0 0 0 99 0 0 0 75 0 0 0 1 0 0 0 248 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 5 0 0 0 226 19 247 191 95 1 0 0 237 65 247 191 228 220
NonclientMetrics=84 1 0 0 1 0 0 0 13 0 0 0 13 0 0 0 18 0 0 0 18 0 0 0 244 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 188 2 0 0 0 0 0 0 0 0 0 0 65 114 105 97 108 0 116 104 101 109 101 0 255 231 0 0 0 0 255 255 255 231 0 0 0 0 0 0 0 0 220 196 15 0 0 0 15 0 0 0 248 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 188 2 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 0 0 0 0 255 255 255 231 0 0 0 0 0 0 0 0 220 196 18 0 0 0 18 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 0 0 0 0 255 255 255 231 0 0 0 0 0 0 0 0 220 196 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 0 0 0 0 255 255 255 231 0 0 0 0 0 0 0 0 220 196 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 0 0 0 0 255 255 255 231 0 0 0 0 0 0 0 0 220 196

[Software\Classes\CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=c:\temp\psion workspace.ico

[Software\Classes\CLSID\{208D2C60-3AEA-1069-A2D7-08002B30309D}\DefaultIcon]
DefaultValue=c:\temp\PSION Netzwerkumgebung.ico

[Software\Classes\CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=c:\temp\psion papierkorb voll.ico
Empty=c:\temp\psion papierkorb leer.ico

[Software\Classes\CLSID\{450D8FBA-AD25-11D0-98A8-0800361B1103}\DefaultIcon]
DefaultValue=c:\temp\PSION Eigene Dateien.ico
