 _____________________________________________________________________________

 LICHTBILD ORDER FORM            August 1995             INTRODUCTORY MATERIAL
 _____________________________________________________________________________

 This order form is a text file named  ORDER.FRM.  You can print it, then fill
 it in by hand. Or you can load it into a text editor (such as DOS EDIT), then
 type your answers before you print it out (using DOS PRINT, for example).
 WHEN SENDING US THE FORM VIA COMPUSERVE,PLEASE DO NOT USE AN ATTACHED UPLOAD;
 that method costs both of us money.   A better way is to paste the  completed
 form into the email line editor (using a paced ASCII upload).  An even easier
 way is to use a CompuServe reader program, such as CIM, OzCIS or TAPCIS.

                                                               Berthold Daum
                                                           lichtbild pty ltd
                                                               21 Margate St
                                                                LPO Box 6011
                                                            Cromer, Vic 3193
                                                                   Australia
                                                        FAX: +61-3-9584 9638
                                                     CompuServe: 100026,3365
                                        INTERNET: 100026.3365@compuserve.com

  ----------------------------- PAYMENT TERMS -------------------------------

  PRICING:               All prices are in Australian dollars. Cheques must be
                         made payable to   lichtbild p/l, Beaumaris, Australia 
                         and must be issued in Australian dollar.  Some inter-
                         national money  orders  (usually via the post office)
                         are also  appropriate.  Eurocheques issued in  German
                         Marks (DEM) (to Berthold Daum) are also accepted.

  CREDIT CARDS:          This is the preferred method of payment. We do accept
                         the following credit cards: American Express, Master-
                         Card, Visa.  You  must fill  out the form provided in
                         this file.


  COMPUSERVE:            For most of our products you can register and pay via
                         CompuServe(GO SWREG). Prices are in US dollar and are
                         a bit higher to cover additional costs.


  CASH PAYMENT:          Mailing cash is not recommended.  However,  since  we
                         can process  currencies from  most countries  with  a
                         population of  twenty million or more,  this might be 
                         the  most  convenient  payment  method for you if you 
                         live outside Australia.  Do  not send coins but round 
                         up to the next banknote value.  Wrap cash payments in
                         dark paper. We do not accept responsibility  for cash 
                         lost in the mail.


  PURCHASE ORDERS:       We accept PO's from  Fortune 1000 companies;  govern-
                         ment offices (state, provincial and national); natio-
                         nally  distributed  media;  plus officially certified
                         service, charitable and educational institutions.


 _____________________________________________________________________________

 LICHTBILD ORDER FORM                                    INTRODUCTORY MATERIAL
 _____________________________________________________________________________



  ----------------------------- DELIVERY ------------------------------------
  

  MAIL:                  We  deliver all  software on 3.5" 1.44 MB floppy disc
                         in PC format  (includes newest versions of all of our
                         shareware)  and the manual by mail.  We charge a flat
                         rate for postage and handling of A$6.00. On demand we
                         email software to any CompuServe address.
                         A surcharge of A$5.00 per product applies.


  ----------------------------- WARRANTY ------------------------------------
  

                         The software is distributed on shareware basis   (try
                         before you buy)  and comes unwarranted.   However, we
                         take pride in fixing  all reported bugs usually with-
                         in a few days. Please report any problems by mail,FAX
                         or email.

  UPDATES:
                         Updates to new versions are free of charge.
                         
                         We upload new versions to CompuServe     (GO PALMTOP,
                         PSION files) and send new versions to PSION BBS's and
                         User Club BBS's all over the world.

                         We send floppies with updated software to  registered
                         users for a small fee (see below).

                         For professional products we send  corrected versions
                         of software free of charge after a bug report  within
                         the first three month after registration.

                         We do not correct outdated, superseded versions.


 _____________________________________________________________________________

 LICHTBILD ORDER FORM                                             PAGE  1 of 2
 _____________________________________________________________________________

         Your name:  _______________________________________________________
                         Given name                     Surname

      Company name:  _______________________________________________________

           Address:  _______________________________________________________

                     _______________________________________________________

       Voice phone:  ____________________   CompuServe ID:  ________________

               Fax:  ____________________     InterNet ID:  ________________

      Where did you  ( ) Author         ( ) CompuServe    ( ) A friend
      get a copy of  ( ) BBS            ( ) InterNet      ( ) Don't remember
      our software?  ( ) Disk vendor    ( ) AOL           ( ) Other, specify
                     ( ) PSION          ( ) GEnie         __________________
      

      Diskette:     ( ) 3.5"  1.44 MB   PC formatted
 
      Host:             ( ) PC          ( ) Mac           ( ) Other, specify
                                                          __________________

      Palmtop:       ( ) PSION S3       ( ) Acorn PowerBook I
                     ( ) PSION S3a      ( ) Acorn PowerBook II

   
      I enclose   ( )  a cheque in A$ to lichtbild p/l, Beaumaris, Australia
                  ( )  an Eurocheque in DM payable to Berthold Daum
                  ( )  money order         
 
      or, please charge this purchase to my credit card.

            ( )  MasterCard     ( )  Visa     ( )  American Express

            My full card number  _ _ _ _  _ _ _ _  _ _ _ _  _ _ _ _ 

                       valid from: __________  until end __________

            Name on card: _________________________________________

            Signature of cardholder: ______________________________


   Do you have comments or suggestions for us?   We would like to hear them!

   _________________________________________________________________________
 _____________________________________________________________________________

 LICHTBILD SOFTWARE ORDER/REGISTRATION                            PAGE  2 of 2
------------------------------------------------------------------------------
 DESCRIPTION                                          AMOUNT    PRICE ENCLOSED
___________________________________________________ _______ ________ ________
 PicPoc V2.4 for S3a                                _______ A$ 49.95 ________
  Paint bitmaps up to 640 x 400 pixels.Pen, Eraser,
  Spray,Fill,Rectangle, Ellipse, Bezier, selectable
  shapes/patterns. Magnifier. Rotate,enlarge, skew.
  Prints to Epson and HP. German/English.
 
 MusiPoc V3.2 for S3a                               _______ A$ 24.95 ________
  A musical editor specialised PSION S3a.  Tunes in
  one or two voices.  Repeat-structures, Animation,   (No printed manual)
  Metronom. Copy, cut, paste, revert, mirror, bars.
  Prints to Epson and HP. German/English. 

 ProPoc V1.4 for S3 and S3a (lite)                  _______ A$ 59.95 ________
  Project management. Multiproject resource sharing
  and schedules,  restdays,  public holidays,  Bud-
  geting, Progress report, Alarms,  Export to WORD,
  HyperPoc link, English.

 ProPoc V1.4 for S3a (professional)                 _______ A$ 99.00 ________
  as above plus:      Cash flow analysis, Export to
  spreadsheet and  AGENDA,  explicite  help  texts, 
  German/English.

 HyperPoc V2.2 for S3 and S3a (lite)                _______ A$ 59.95 ________
  Hypercard/multimedia application.   Variable card
  size; backgrounds;  text, icons, bitmaps, alarms,
  clocks, tunes, waves, animation; automatic hyper-
  text;  OPL-interface;   export text  and bitmaps.
  English.
  
 HyperPoc V2.2 for S3a (professional)               _______ A$ 99.00 ________
  as above plus: import of text and WORD files, im-
  proved  performance,extensive help  files, PROPOC
  link,royalty free runtime licence.German/English.

 RepPoc V2.3 for S3 and S3a (lite)                  _______ A$ 39.95 ________
  Merge data from DATA files,WORD forms.Create let-
  ters,envelops, faxes, lists,labels. Column arith-
  metic.Sorting & break processing. German/English.
  
 RepPoc V2.3 for S3 and S3a (professional)          _______ A$ 59.00 ________
  as above plus:   export to spreadsheet. Extensive
  help texts. German/English.

 PocDoc V1.2 for S3 and S3a                         _______ A$ 19.95 ________
  Electronic diary to monitor your health.  Charts, 
  printing, emergency dialing. German/English.         (No printed manual)
 
 F11 V1.2 for S3a                                   _______ A$ 19.95 ________
  Typing aid for WORD processor.  Automatic spaces,
  upper case, double hyphen.  Insertion of phrases/  
  data/spreadsheet.German version with easy umlauts.
  Character table. Find file. German/English.          (No printed manual)

 S3a Powerpack   includes:                          _______ A$199.00 ________
  ProPoc prof, HyperPoc prof, PicPoc, MusiPoc.

 S3a Wordpack (RepPoc prof, F11)                    _______ A$ 69.00 ________

 5-packs  - ProPoc V1.4 prof for S3a                _______ A$399.00 ________
          - HyperPoc V2.2 prof for S3a              _______ A$399.00 ________
          - S3a Powerpack                           _______ A$799.00 ________
          - S3a Wordpack                            _______ A$249.00 ________

 Toolpack for developers (S3a only)                 _______ A$ 99.00 ________
  Decompiler for OPL applications. Help compiler
  for Morpheus help server. SetUp utility. Memory
  spy, dump utility, tech tips.

 Updates:                - Floppy with newest versions      A$ 14.00 ________
                         - any new manual               ___ A$  6.00 ________

 Postage (if we have to mail manual/floppy)                 A$  6.00 ________
 Email surcharge per product                            ___ A$  5.00 ________
 (if you want program to be send by email)
 ___________________________________________________________________ ________
 
 TOTAL_______________________________________________________________ ________
 FROM:  ________________________                                     --------
                                                                    | Please |
        ________________________                                    | affix  |
                                                                    | stamp  |
        ________________________                                    | here   |
                                                                    |        |
                                                                     --------



                                lichtbild pty ltd
                                LPO Box 6011
                                Cromer, Vic 3193
                                Australia





 _                                                                           _






 [D]

        +------ TO MAKE AN ENVELOPE, FOLD THIS PAGE AS FOLLOWS: ------+
        |                                                             |
        | 1) Put other pages under this page                          |
        | 2) Fold [FLAP A] under, using line [B]                      |
        | 3) Fold [C] under, so that line [B] meets top edge of paper |
 [D]    | 4) Tape at [C] and [D]                                      |
        | 5) Slide in enclosures (cards, cheques, etc.)               |
        | 6) Tape envelope closed                                     |
        | 7) Affix stamp                                              |
        |                                                             |
        +-------------------------------------------------------------+

                                     [C]
 [B] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - [B]





                                   FLAP  A




