[SiboPO]
ID=9
; hostid of last time connection dialog was invoked
Host=9
PO=M:
Version=1

[Host]
ID=9
Name=Internet
Vendor=Internet
MTA=1
Send=1
Receive=1
Mark=1
EnableAttach=2
MsgKLimit=30
TotalKLimit=100
AttachKLimit=50
Dyl=INT
Session=1
SendReceipt=1
DeleteMsg=1

[MTA]
;256*id+1
ID=2305
Name=Dialup
PO=
MTA=SYS$IMTA
Dyl=INT
Tel=
Country=United Kingdom
Area=London Inner

[Apps]
DBF=Data;;ROM::DATA.APP
WRD=Word;;ROM::WORD.APP
OPL=Program;OROPO;ROM::WORD.APP
SPR=Sheet;;ROM::SH3.APP
AGN=Agenda;;ROM::AGENDA.APP
TXT=Word;$;ROM::WORD.APP
WVE=Record;;ROM::RECORD.APP

[Paths]
DBF=M:\DAT\
AGN=M:\AGN\
WLD=M:\WLD\
SPR=M:\SPR\
WRD=M:\WRD\
WVE=M:\WVE\
OPL=M:\OPL\
OPA=M:\APP\
APP=M:\APP\
IMG=M:\IMG\
