Kanton/Land: 
Orte: Nord
Orte: Ost/Zentral/SÅd
Orte: West/NachbarlÑnder
31
ZHBELUURSZOWNWGLZGFRSOBSBLSHARAISGGRAGTGTIVDVSNEGEJUDDFFIIOOFL
ZÅrich
Bern
Luzern
Uri
Schwyz
Obwalden
Nidwalden
Glarus
Zug
Fribourg
Solothurn
Basel-Stadt
Basel-Landschaft
Schaffhausen
Appenzell A. Rh.
Appenzell I. Rh.
St. Gallen
GraubÅnden
Aargau
Thurgau
Ticino
Vaud
Valais
NeuchÉtel
Genäve
Jura
Deutschland
Frankreich
Italien
ôsterreich
FÅrstentum Liechtenstein

