Canton/Country: 
Places: North
Places: East/Central/South
Places: West/Near Countries
31
ZHBELUURSZOWNWGLZGFRSOBSBLSHARAISGGRAGTGTIVDVSNEGEJUDDFFIIOOFL
Zurich
Berne
Lucerne
Uri
Schwyz
Obwalden
Nidwalden
Glarus
Zug
Fribourg
Solothurn
Basel-Stadt
Basel-Landschaft
Schaffhausen
Appenzell A. Rh.
Appenzell I. Rh.
St. Gallen
GraubÅnden
Aargau
Thurgau
Ticino
Vaud
Valais
NeuchÉtel
Geneva
Jura
Germany
France
Italy
Austria
Liechtenstein

