[Global]
;
;  SMTP authentication
;
;  Change the following line to interface=all or any other ip address
;  if you want SmtpAuth to listen on other ports as well.
;  On EPOC this will cause a dialup request!
;
interface=localhost

[Server 1&1]
active=yes
listen-port=1025
server=smtp.1und1.com
port=25
user=user name
password=password

[Server isp2]
active=no
listen-port=1026
server=smtp.isp2.com
port=25
user=user name 2
password=password 2
;
;  add this only if you want POP before SMTP authentication!
;
;pop-server=pop.smtp2.com
;pop-port=110



