Commander v1.2
/Psion Series 5/
-------------------

Ez egy ingyenes filekezelo program. 
Használd, másold, terjeszd nyugodtan az ezen file végén olvashatóak figyelembevételével!


Billentyuk:

- Kurzor fel, le, jobbra, balra, PgUp, PgDn, Home, End
- Ablakok közötti váltás: TAB
- Kijelölés: space, +, -, * billentyukkel
- Drive váltás: bal ablak: Ctrl+1 (Ctrl+X), jobb ablak: Ctrl+2 (Ctrl+Y)

Funkciók:

- Másolás: Ctrl+C
- Átmozgatás: Ctrl+M
- Törlés: Ctrl+D
- Átnevezés: Ctrl+Z
- Új folder: Ctrl+N
- File/folder attributumok beállítása: Ctrl+A
- Info akt. drive-ról, folder-ról: Ctrl+I
- Info alkönyvtárstruktúráról: Ctrl+T
- File megtekintés: Ctrl+V
- File szerkesztés: Ctrl+O
- File/folder keresés: Ctrl+F
- Rendezés képernyon: Ctrl+S (rendezetlen, név szerint, méret szerint)
- Képernyo frissítés: Ctrl+R
- Tree-view: Ctrl+W (kurzor le, föl, Home, End, Enter)
- Task lista: Ctrl+L
- Program indítás (jelen verzióban csak a ROM-ban lévo programokra, ill. általuk létrehozott file-okra /pl. egy Word file,.../) : Enter
- Angol nyelvu segítség: Ctrl + H
- Kilépéskor állapotok mentése


Toll használata:

- File-ra / folder-re egy klikk: aktuálissá teszi az adott sort (inverz megjelenítés)
- Folder bejegyzésre második klikk: folder kibontása (belépés az alkönyvtárba)
- File-ra második klikk: file indítása (ha egy ROM alkalmazás a "tulajdonosa")
- File-ra / folder-re egy klikk lenyomott Ctrl billentyuvel: egyenkénti kijelölés (A menü ikon alatti "ollós" ikon is ugyanaz.)
- Drive váltás: Klikk az ablakok felso sorában lévo aktuális folder kijelzésében található drive-ra
- Csoportos kijelölés, invertálás: klikk az ablakok alsó sorában lévo folder/file darabszám kijelzésre.
- Lapozás: Klikk az ablakok jobb felso és alsó sarkában lévo "nyilakra". Lenyomott Ctrl billentyuvel elso, ill. ut. sorra ugrik.

- Fentiek (kivéve a drive-váltást) ha nem az aktuális ablakban történnek, eloször csak ablakváltást eredményeznek.


                                    # @

Megjegyzés:	Amennyiben sokallod a grafikák által elfoglalt 13281 byte-ot, 
		nyugodtan töröld le a Commander.mbm file-t. 
		A program nélküle is mûködik.


Addig is, gond, probléma esetén, vagy ha ötleted van, kérlek írj:  sarlos@finit.hu

Honlap: www.integra.hu/private/sarlos

GARANCIA, FELELOSSÉG, SZERZOI JOGOK:
A PROGRAMRA SEMMILYEN GARANCIA NEM JÁR, A SZERZO SEMMILYEN FELELOSSÉGET NEM VÁLLAL AZ ESETLEGESEN BEKÖVETKEZETT ANYAGI ÉS NEM ANYAGI JELLEGU KÁROKÉRT, ADATVESZTÉSEKÉRT. A PROGRAMOT MINDENKI CSAK A SAJÁT FELELOSSÉGÉRE HASZNÁLJA!
A SZERZO MINDEN JOGOT FENNTART MAGÁNAK! A PROGRAM VISSZEFEJTÉSE, DEKÓDOLÁSA, ÉRTÉKESÍTÉSE, A KÓD EGÉSZÉNEK VAGY EGYES RÉSZEINEK ELTULAJDONÍTÁSA ÉS FELHASZNÁLÁSA SZERZOI JOGOKAT SÉRT, TEHÁT TILOS!!!.
