Commander v1.1 
/Psion Series 5/
-------------------

Ez egy ingyenes filekezelo program. 
Használd, másold, terjeszd nyugodtan az ezen file végén olvashatóak figyelembevételével!


Billentyuk:

- Kurzor fel, le, jobbra, balra, PgUp, PgDn, Home, End
- Ablakok közötti váltás: TAB
- Kijelölés: space, +, -, * billentyukkel
- Drive váltás: bal ablak: CTRL+1, jobb ablak: CTRL+2

Funkciók:

- Másolás: CTRL+C
- Átmozgatás: CTRL+M
- Törlés: CTRL+D
- Átnevezés: CTRL+Z
- Új folder: CTRL+N
- File/folder attributumok beállítása: CTRL+A
- Info akt. drive-ról, folder-ról: CTRL+I
- Info alkönyvtárstruktúráról: CTRL+T
- File megtekintés: CTRL+V
- File szerkesztés: CTRL+E
- File/folder keresés: CTRL+F
- Rendezés képernyon: CTRL+S (rendezetlen, név szerint, méret szerint)
- Képernyo frissítés: CTRL+R
- Tree-view: CTRL+W (kurzor le, föl, Home, End, Enter)
- Task lista: CTRL+L
- Program indítás (jelen verzióban csak a ROM-ban lévo programokra, ill. általuk létrehozott file-okra /pl. egy Word file,.../) : Enter
- Angol nyelvu segítség: CTRL + H
- Kilépéskor állapotok mentése

Jelen verzióban a toll csak korlátozottan használható. A nyomógombok, checkbox-ok, menü esetén muködik (ehhez nem kellett programozni), de navigálásra, file kijelölésre csak a billentyuzetet használhatod.

Megjegyzés:	Amennyiben sokallod a grafikák által elfoglalt 13281 byte-ot, 
		nyugodtan töröld le a Commander.mbm file-t. 
		A program nélküle is mûködik.


Addig is, gond, probléma esetén, vagy ha ötleted van, kérlek írj:  sarlos@finit.hu

Honlap: www.finit.hu/private/sarlos

GARANCIA, FELELOSSÉG, SZERZOI JOGOK:
A PROGRAMRA SEMMILYEN GARANCIA NEM JÁR, A SZERZO SEMMILYEN FELELOSSÉGET NEM VÁLLAL AZ ESETLEGESEN BEKÖVETKEZETT ANYAGI ÉS NEM ANYAGI JELLEGU KÁROKÉRT, ADATVESZTÉSEKÉRT. A PROGRAMOT MINDENKI CSAK A SAJÁT FELELOSSÉGÉRE HASZNÁLJA!
A SZERZO MINDEN JOGOT FENNTART MAGÁNAK! A PROGRAM VISSZEFEJTÉSE, DEKÓDOLÁSA, ÉRTÉKESÍTÉSE, A KÓD EGÉSZÉNEK VAGY EGYES RÉSZEINEK ELTULAJDONÍTÁSA ÉS FELHASZNÁLÁSA SZERZOI JOGOKAT SÉRT, TEHÁT TILOS!!!.
