// menubuilder.h
// Generated by Menu Builder


case EEikCmdExit:
    Exit();
	break;


case EContsyncSynchronise:
	{
	iModel->ConnectL();
	iModel->OpenDatabaseL();
	iModel->SynchroniseL(iEikonEnv);
	break;
	}
	

case EContsyncOptions:
	{
	COptionsDialog* optionsDialog = new(ELeave) COptionsDialog(iModel);
	//CleanupStack::PushL(optionsDialog);
	optionsDialog->ExecuteLD(R_OPTIONS_DIALOG);
	//CleanupStack::PopAndDestroy();
	break;
	}


