[batch]
; Always executed on startup
auto=autorcom.bat
; Used to search for batch files
path=path
; Used to give the default extension for batch files
ext=.bat

[rcom]
; Used to make the interpreter no print anything
quiet=off
; Used to set RFM into server mode
server=off
; Current remote computer model, used by setup
model=HC
; Path for backup drives, used by setup
path=c:\psion
; List of initial substitutes, used by setup and backup
;   The first letter in the string is Y or N
;   meaning include in the backup Yes or No.
subst1=yl:-rem::a:\
subst2=yi:-rem::m:\
subst3=yr:-rem::b:\
subst4=
subst5=

[rprint]
; Sets the default printer for rprint.exe
printer=lpt1
timeout=2
baud=9600

[setup]
; Various definitions used by the setup program
model1=MC-19200-ABCDM-LMRSI
model2=HC-9600-ABM-LRI
model3=Series3-9600-ABCM-LR*I
model4=Series3a-19200-ABCM-LR*I
model5=Other-19200-ABCDM-LMRSI
baud=19200-9600-4800-2400-1200
port=COM1-COM2-COM3-COM4
printer=LPT1-LPT2-LPT3-COM1-COM2-COM3-COM4
pbaud=9600-4800-2400-1200

[rem]
; Enable the remote filing system
Enabled=on
; Wait for the link to establish before running batch
wait=off
; The baud rate if physical is an RS232 device
Baud=9600
; The media layer driver.
Media=MAS:
; The link layer driver.
Link=LLC:
; The physical layer driver.
; eg Physical=COM1
